### ISSUE TITLE
Create group

### ISSUE THREAD

**Issue by not-so-smart** [groupme-js/node-groupme#7]
`GroupManager#create(options: GroupCreateOptions): Promise<Group>`

Creates a new group.
It would probably be worth describing the `GroupCreateOptions` object, but I'll decide on that later.

Usage:
```js
client.groups.create({ name: "my awesome group" })
```

**Comment by striker4150** [comment]
Hi, I created a PR to add this feature. Please let me know if you have any suggestions.

**Comment by not-so-smart** [comment]
> Hi, I created a PR to add this feature. Please let me know if you have any suggestions.

Thanks so much! I'll check it out
